server:
  port: 8089

api:
  version: v1

base:
  path: ${api.version}/api/market

spring:
  cloud:
    config:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    feign:
      Request: DEBUG
      Response: DEBUG
    br.com.market: DEBUG

feign:
  client:
    httpclient:
      enabled: true
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

clients:
  paths:
    products: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json
    purchases: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json

management:
  server:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: spring-market