server:
  port: 8089
  servlet:
    context-path: /v1/api/market

api:
  version: v1

spring:
  cloud:
    config:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    feign:
      Request: DEBUG
      Response: DEBUG
    br.com.market: DEBUG
    br.com.market.adapter.out.web.feing: DEBUG
    org.springframework.cloud.openfeign: DEBUG

feign:
  client:
    httpclient:
      enabled: true
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

clients:
  paths:
    products: https://run.mocky.io/v3/08a33394-a498-4fae-9d51-8b75fd971f19
    purchases: https://run.mocky.io/v3/2fcefb23-83fa-4d2a-88a4-927f3ebd0dd7
